### ISSUE TITLE
datapath introspection in python2

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/deriva-py#54]
This only affects python 2.7; it works fine in python 3.6:

>>> from deriva.core import ErmrestCatalog
>>> catalog = ErmrestCatalog('https', 'dev.rebuildingakidney.org', 2)
>>> pb = catalog.getPathBuilder()
>>> dir(pb)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/deriva/core/datapath.py", line 82, in __dir__
    return list(super(Catalog, self).__dir__()) + [key for key in self.schemas if _isidentifier(key)]
AttributeError: 'super' object has no attribute '__dir__'

This causes problems when trying to use the datapath library with reticulate in RStudio with python2 (but you can tell RStudio to use python3, in which case everything works).

**Comment by karlcz** [comment]
I think this is a duplicate of #20 ?
